# Generated by Django 5.2.4 on 2025-07-25 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('project_advisor', models.CharField(max_length=150)),
                ('project_data', models.DateTimeField(auto_now_add=True)),
                ('project_location', models.CharField(max_length=300)),
                ('project_institution', models.CharField(max_length=150)),
                ('project_colaborator', models.ManyToManyField(blank=True, null=True, related_name='Colaboradores', to=settings.AUTH_USER_MODEL)),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterPlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=150)),
                ('plant_popular_name', models.CharField(blank=True, max_length=150)),
                ('plant_id', models.PositiveIntegerField(editable=False)),
                ('plant_photo', models.ImageField(blank=True, null=True, upload_to='plants/')),
                ('num_individuals', models.PositiveIntegerField()),
                ('num_flowers', models.PositiveIntegerField(blank=True, default=0)),
                ('scent', models.CharField(choices=[('1', 'Idiopático'), ('2', 'Simpático')], max_length=10)),
                ('resources', models.CharField(blank=True, max_length=150)),
                ('data_register', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanTracker.registerprojectmodel')),
            ],
        ),
    ]
