# Generated by Django 5.2.4 on 2025-07-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanTracker', '0002_alter_registerprojectmodel_project_colaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterVisitorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='registerplantmodel',
            name='plant_id',
            field=models.CharField(editable=False),
        ),
    ]
