# Generated by Django 5.2.4 on 2025-08-01 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanTracker', '0003_registervisitormodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registervisitormodel',
            name='behavior',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='flowers_visitor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='num_visitor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitors/'),
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanTracker.registerplantmodel'),
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='popular_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='resources_visitor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='type_visitor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='visitor_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
