# Generated by Django 5.2.4 on 2025-08-01 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanTracker', '0004_registervisitormodel_behavior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervisitormodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registervisitormodel',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='registervisitormodel',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='registervisitormodel',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='registervisitormodel',
            name='num_visitor',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='registervisitormodel',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanTracker.registerplantmodel'),
        ),
        migrations.AlterField(
            model_name='registervisitormodel',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='registervisitormodel',
            name='visitor_id',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
