# Generated by Django 5.2.4 on 2025-08-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanTracker', '0005_alter_registervisitormodel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registervisitormodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registervisitormodel',
            name='use_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registervisitormodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registervisitormodel',
            name='flowers_visitor',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='registervisitormodel',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
